name: Fly Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if : ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    if : ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy_notification:
    needs: [deploy]
    runs-on: ubuntu-latest
    if : ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: The last commit was deployed successfully! Last commit by ${{ github.event.head_commit.author }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: The last commit failed to deploy. Last commit by ${{ github.event.head_commit.author }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  
