name: periodic health check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check   
        uses: Jtalk/url-health-check-action@v3.2
        with:
          url: https://pokedex-1.fly.dev/

